### ISSUE TITLE
okta-hosted-login

### ISSUE THREAD

**Issue by ave-303** [okta/samples-aspnet-webforms#24]
Setting the Project's Target Framework to .NET Framework 4.7.2 creates a runtime error:

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=Okta.AspNet
  StackTrace:
   at Okta.AspNet.OpenIdConnectAuthenticationOptionsBuilder..ctor(OktaMvcOptions oktaMvcOptions, IUserInformationProvider userInformationProvider)
   at Okta.AspNet.OktaMiddlewareExtensions.AddOpenIdConnectAuthentication(IAppBuilder app, OktaMvcOptions options)
   at Okta.AspNet.OktaMiddlewareExtensions.UseOktaMvc(IAppBuilder app, OktaMvcOptions options)
   at okta_aspnet_webforms_example.Startup.Configuration(IAppBuilder app) in ...\okta-hosted-login\okta-aspnet-webforms-example\Startup.cs...
```

The origin appears to be in "Okta.AspNet"; however updating via NuGet doesn't resolve the problem.

Any ideas on how get this solution to work in .NET 4.7.2?

Thanks

**Comment by bryanapellanes-okta** [comment]
@ave-303,
Thank you for your inquiry.  We have added to our backlog an item to update all samples to the latest relevant framework version to solve this for future users of the samples.  I am currently reviewing this to determine appropriate approach to manually updating the framework version in the sample in question.  I'll provide an update here when I have more information to share.

**Comment by bryanapellanes-okta** [comment]
@ave-303,
In the short term it seems your best bet will be to start a new Asp.Net project that targets your framework of choice then copy the sample files into the project.  We will prioritize internally to update the samples.
